### ISSUE TITLE
Setup changesets

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jspsych-contrib#2]
I'm assuming that our recommendation is that folks load plugins/extensions from this repo via `unpkg.com` links. How do we trigger a release of a package in this repo?

**Comment by jodeleeuw** [comment]
Nope, that sounds good. When you implement this can you edit the readme file as well to describe how to add a changeset to the PR?

And am I following correctly that if we merge a PR with a changeset in this repo then it will generate the release right away?

**Comment by bjoluc** [comment]
> And am I following correctly that if we merge a PR with a changeset in this repo then it will generate the release right away?
Close, we'll still have the "Version Packages" PR then that we need to merge to do the release.

**Comment by bjoluc** [comment]
Done with 5d2a0ea9
