### ISSUE TITLE
Mediapipe face tracking extension

### ISSUE THREAD

**Issue by mgrewe** [jspsych/jspsych-contrib#40]
Hi all, 
I'm currently trying to implement a mediapipe face tracking extension for jsPsych, but a runtime error keeps me from moving on. I added ```@mediapipe/face_mesh``` as an dependency and try to instantiate it in the constructor of the new ```jsPsychExtensionMediapipeFacemesh```. However, I'm stuck with the VM throwing the error ```Uncaught TypeError: face_mesh.FaceMesh is not a constructor```.

I suspect that it is related to the way of handling dependencies by npm and that not all parts of mediapipe were included in the dist js file created by npm. Because I'm fairly new to JS/TS and npm, I greatly appreciate any help.

Please find an example here: https://github.com/mgrewe/jspsych-contrib/tree/mediapipe_test

Thanks!

**Comment by bjoluc** [comment]
Hi @mgrewe,
I'll have a look at this today. Would you be willing to open a draft PR already so we can comment on code and push to your branch? Thanks!

**Comment by mgrewe** [comment]
Hi @bjoluc 

thanks for reaching out. Find the draft PR here: https://github.com/jspsych/jspsych-contrib/pull/41

Cheers

**Comment by bjoluc** [comment]
Thanks! :rocket:
