### ISSUE TITLE
Latest version of html-vas-response doesn't seem to be on NPM?

### ISSUE THREAD

**Issue by kinleyid** [jspsych/jspsych-contrib#59]
Hello, it seems like the latest version (1.1.0) of html-vas-response is not on NPM. `<script src="https://unpkg.com/@jspsych-contrib/plugin-html-vas-response@1.1.0"></script>` returns a 404 error and `<script src="https://unpkg.com/@jspsych-contrib/plugin-html-vas-response"></script>` appears to load version 1.0.0. Do I need to do anything to update it?

**Comment by bjoluc** [comment]
Good catch, I guess the tooling chokes on
https://github.com/jspsych/jspsych-contrib/blob/56d639ccb54df932605869a0bfcc4aa30d7a10fb/packages/plugin-html-vas-response/package.json#L4
because `Boolean("false") === true` – let me remove that and see what happens...

**Comment by bjoluc** [comment]
:+1:
