### ISSUE TITLE
add optional message to wait screen for pipe plugin

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jspsych-contrib#81]
As suggested here: https://github.com/jspsych/datapipe/issues/89

**Comment by DominiqueMakowski** [comment]
Would it be "as simple" as adding somewhere in here:

https://github.com/jspsych/jspsych-contrib/blob/ae86a8ef70d0e29eb7fc773f1f6d0064036eff41/packages/plugin-pipe/src/index.ts#L110-L114

```
"<p>Saving data. Please do not close this page yet!</p>"
```
