### ISSUE TITLE
make it clearer how to browse the list of plugins available here.

### ISSUE THREAD

**Issue by jodeleeuw** [jspsych/jspsych-contrib#9]
I think it may not be intuitive for some folks to look in `/packages`.

We could either add a list to the README that folks can update when they contribute, or we could just add a general statement about looking in `/packages` to the README.

**Comment by bjoluc** [comment]
Right. I'm in favor of having a table in the readme, similar to https://www.jspsych.org/7.0/plugins/list-of-plugins/.

**Comment by jodeleeuw** [comment]
Great, thanks @becky-gilbert!

I think in the main repo the docs page is clear and it's probably better to not have to duplicate the effort. I also like that it might nudge people into the docs where lots more info is available.
